# Generating a Fake Data for The Revenue Optimization Problem

Because Data is rarely available to test the performance of Algorithms in real world scenarios, synthetic datasets play an important role. This is important because the problem can be scaled up or down to study the behaviour of the Algorithm. In Our case we want to generate data for queries available for a said number of companies who need to pay an advertisement fee for display of thier add when the query is requeste.

To Define the problem. We need to Know first the number of companies and the number of queries available. Also each company has a total budget and a price tag for each query (Price per click). 

NC = Number of Companies

NQ = Number of Queries

CB = Company budgets

PPC = Price per click  (NC X NQ matrix)

First we will Define the Number of Companies and Queries then randomly Company budget and thier corresponding price per click

In [1]:
# Number of Companies and Number of Queries

NC = 10
NQ = 12

In [2]:
# Generate Company Budget

import numpy as np

def Generate_company_budget(NC, BR = (200, 2000)):
    """ NC: number of companies an interger
        BR: Budget range and is a tuple (lower bound, upper bound)
    returns a list the size of number of companies with 
    randomly assigned budgets"""
    
    return np.random.randint(BR[0],BR[1], NC)

In [3]:
Generate_CB(NC)

array([1460,  241, 1903, 1338,  402,  771,  280, 1929, 1437,  323])

In [17]:
def Generate_price_per_click(NC, NQ, PR = (1, 5)):
    """ PR: the price per click range. Has to be lower than company budget
    
    returns an NC X NQ array"""
    
    return np.random.randint(PR[0],PR[1], (NC,NQ))
    

In [18]:
Generate_price_per_click(NC, NQ)

array([[4, 4, 4, 2, 4, 2, 3, 3],
       [1, 3, 2, 1, 1, 4, 1, 1],
       [1, 1, 4, 1, 1, 3, 3, 1],
       [4, 2, 2, 3, 3, 3, 2, 1],
       [3, 1, 3, 3, 1, 1, 1, 3]])

# Click Through Rate (CTR) and Average Price Per Display (APD)

For each company its click through rate for a given query is defined and used to determine the average price for display of an add. CTR for a company and query falls in the range 0 to 1. this is the probability of a user clickking on the add of a given company. CTR is generated randomly and ADP is calculated by multiplying the PPC by CTR element wise.

In [19]:
# generate the CTR.

def Generate_CTR(NC, NQ):
    """ returns an NC by NQ array with probabilities"""
    
    return np.random.random((NC, NQ))

In [20]:
Generate_CTR(NC, NQ)

array([[0.54325216, 0.30126533, 0.40562573, 0.87845739, 0.26402799,
        0.30509854, 0.09482833, 0.47048752],
       [0.50754717, 0.88142103, 0.71709913, 0.74581785, 0.47558403,
        0.94649355, 0.38602954, 0.90601337],
       [0.93485283, 0.35387092, 0.59177327, 0.52608545, 0.52464672,
        0.00645059, 0.88378089, 0.13427036],
       [0.3701752 , 0.95330529, 0.7434753 , 0.92385016, 0.71959266,
        0.63209925, 0.31174727, 0.44528791],
       [0.79041448, 0.89046867, 0.7401891 , 0.54371791, 0.7421909 ,
        0.359539  , 0.59464645, 0.93521934]])

In [21]:
# get the APD

def Get_APD(PPC, CTR):
    """ multiplies PPC and CTR element wise
    returns an array same size as PPC and CTR """
    
    return np.multiply(PPC, CTR)

# Generate Query Estimates

Query estimates are the total number of queries users will request for a period of time or period of advertisement. The query estimates is an array the lenght of the queries 

In [22]:
# generate query estimates 

def Generate_QE(NQ, ER = (200, 500)):
    """ ER: query estimate range
    retuens a 1D array the lenth of NQ"""
    
    return np.random.randint(ER[0], ER[1], NC)

In [23]:
Generate_QE(NQ)

array([296, 389, 484, 389, 473])

# An Example Data generation 


To generate data, the following procedure is followed 
1. Define NC and NQ
2. Generate PPC, CB, QE
3. Generate CTR
4. Calculate APD from PPC and CTR

In [11]:

NC, NQ = 5, 8

CB, QE = Generate_CB(NC), Generate_QE(NQ) 

PPC = Generate_PPC(NC, NQ)

CTR = Generate_CTR(NC, NQ)

APD = Get_APD(PPC, CTR)


In [12]:
CB

array([1566,  255, 1468, 1182, 1192])

In [13]:
QE

array([380, 290, 226, 302, 379])

In [14]:
PPC

array([[15, 12, 16,  7,  6,  2,  2, 13],
       [13, 10,  7, 17, 13,  4,  2, 11],
       [19, 13, 17, 11,  5, 11,  6, 10],
       [ 9,  3,  6, 18, 17, 14,  4, 14],
       [14,  1,  1,  8, 16,  9,  2, 14]])

In [15]:
CTR

array([[0.65211812, 0.05783347, 0.57972956, 0.84765235, 0.85649763,
        0.20432095, 0.1987608 , 0.8933966 ],
       [0.60272904, 0.00294913, 0.32264908, 0.57080743, 0.79701698,
        0.66047911, 0.46176423, 0.28961006],
       [0.29031473, 0.82580957, 0.03244858, 0.81160736, 0.59417325,
        0.70330846, 0.33506832, 0.69260504],
       [0.06380665, 0.61726793, 0.07201708, 0.20972453, 0.06177231,
        0.91162626, 0.1362017 , 0.96274972],
       [0.07100261, 0.76968084, 0.44171631, 0.41531391, 0.46621272,
        0.41244427, 0.27445686, 0.65211033]])

In [16]:
APD

array([[ 9.78177183,  0.69400168,  9.27567303,  5.93356646,  5.13898577,
         0.40864189,  0.39752159, 11.61415574],
       [ 7.83547746,  0.02949129,  2.25854355,  9.70372638, 10.36122077,
         2.64191644,  0.92352846,  3.18571066],
       [ 5.51597991, 10.73552446,  0.5516258 ,  8.92768092,  2.97086623,
         7.73639307,  2.01040995,  6.92605035],
       [ 0.57425981,  1.85180378,  0.43210247,  3.77504146,  1.05012928,
        12.76276768,  0.5448068 , 13.4784961 ],
       [ 0.99403647,  0.76968084,  0.44171631,  3.32251127,  7.4594035 ,
         3.71199841,  0.54891371,  9.12954463]])